version: "3.9"

networks:
  rag_network:
    driver: bridge

services:
  ollama:
    container_name: ollama
    build:
      context: .
      dockerfile: DockerfileLLM
    # Para Docker Compose local:
    gpus: all
    # Para Swarm (opcional, si lo usás):
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - OLLAMA_MAX_GPU_MEM=14GB
      - OLLAMA_ORIGINS=http://rag-service:5000
    volumes:
      - ollama-models:/home/app/.ollama/models
    ports:
      - "11434:11434"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 5s
      retries: 3
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    stop_grace_period: 30s
    networks:
      - rag_network

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:v1.15.1
    ports:
      - "6333:6333"
      # - "6334:6334"  # gRPC opcional
    volumes:
      - qdrant_data:/qdrant/storage
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/ready"]
      interval: 30s
      timeout: 5s
      retries: 3
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    stop_grace_period: 30s
    networks:
      - rag_network

  rag-service:
    container_name: rag-service
    build:
      context: .
      dockerfile: DockerfileRAG
    depends_on:
      - ollama
      - qdrant
    environment:
      - OLLAMA_URL=http://ollama:11434
      - QDRANT_URL=http://qdrant:6333
      - RAG_PROFILE=host        # usa embeddings/params de perfil GPU
      # - QDRANT_USE_GRPC=True  # si exponés 6334 y querés gRPC
    ports:
      - "5000:5000"
    volumes:
      - rag-data:/app/data
      - rag-output:/app/output
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    stop_grace_period: 30s
    networks:
      - rag_network

volumes:
  ollama-models:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/rag/ollama/models

  rag-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/rag/data

  rag-output:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/rag/output

  qdrant_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/rag/qdrant
